1. Write a Python Program to Add Two Matrices?
2. Write a Python Program to Multiply Two Matrices?
3. Write a Python Program to Transpose a Matrix?
4. Write a Python Program to Sort Words in Alphabetic Order?
5. Write a Python Program to Remove Punctuation From a String?

In [5]:
import numpy as np

In [4]:
#1. Adding two matrices

mat_1 = [[1,2,3],[4,5,6],[7,8,9]]
mat_2 = [[2,3,4],[5,6,7],[8,9,10]]

#For matrix addtion and multiplication the dimension should be equal for both the matrices

sum_mat = []
for i in range(len(mat_1)):
    temp_lst = []
    for j in range(len(mat_1[0])):
        temp_lst.append(mat_1[i][j] + mat_2[i][j])
    sum_mat.append(temp_lst)
print(sum_mat)

[[3, 5, 7], [9, 11, 13], [15, 17, 19]]


In [11]:
#Doing the same in numpy
arr_1 = np.array(mat_1)
arr_2 = np.array(mat_2)

print(arr_1 + arr_2)

[[ 3  5  7]
 [ 9 11 13]
 [15 17 19]]


In [16]:
#3. transpose of a matrix
mat = [[1,2,3],[4,5,6],[7,8,9]]

def mat_trans(mat):
    mat_t = []
    for i in range(len(mat)):
        temp_lst = []
        for j in range(len(mat[0])):
            temp_lst.append(mat[j][i])
        mat_t.append(temp_lst)
    return mat_t
print(mat_trans(mat))

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]


In [14]:
#numpy implementation of transpose
print(np.transpose(np.array(mat)))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [26]:
#2. matrix multiplication 
mat_1 = [[1,2,3],[4,5,6],[7,8,9]]
mat_2 = [[2,3,4],[5,6,7],[8,9,10]]
mat_mul = []
mat_2_T = mat_trans(mat_2)

for i in range(len(mat_1)):
    temp_lst = []
    for j in range(len(mat_2_T)):
        sum = 0
        for k in range(len(mat_2_T[0])):
            sum += mat_1[i][k]*mat_2_T[j][k]
        temp_lst.append(sum)
    mat_mul.append(temp_lst)
print(mat_mul)

[[36, 42, 48], [81, 96, 111], [126, 150, 174]]


In [27]:
#Doing the same in numpy
arr_1 = np.array(mat_1)
arr_2 = np.array(mat_2)
print(np.matmul(arr_1,arr_2))

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


In [45]:
#4. Write a Python Program to Sort Words in Alphabetic Order
words = ['Little','Taugh','Teu','People']

#using the list implementation
words.sort()

print(words)
    

['Little', 'People', 'Taugh', 'Teu']


In [64]:
#5. Write a Python Program to Remove Punctuation From a String

import string
punc = string.punctuation
sentence = "Wow! it was truly nice, but the tip-off offered was bad (not adequate)."
txt = sentence
for char in sentence:
    if char in punc:
        txt = txt.replace(char,"")
print(txt)

Wow it was truly nice but the tipoff offered was bad not adequate
